name: Build DesignerTools APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant Gradlew execute permission
        run: chmod +x ./gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: List all APKs
        run: find app/build -name "*.apk"

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: DesignerTools-debug
          path: app/build/outputs/apk/debug/DesignerTools-*-debug.apk

